### ISSUE TITLE
ensure all integration tests pass, at least when run individually

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/infrastructure-integration-test#103]
1.  Are there integration tests that always fail, even if run individually?

If so, they need to be rewritten to pass.
- is there a way to write the test so it passes more reliably?
- is the failing part of the test actually testing integration across services?  
    - If it is not testing cross service integration, can the failing part of the integration test be put in the relevant code base's test suite, and removed from the integration test?
- is there utility in having the test suite run, possibly with a "skip" at the point in the test when they always fail ... so we can at least execute the part that works?

From infradev meeting May 26, 2020 https://docs.google.com/document/d/1gckL1V0Iw6Vih7FO_-UXMJqbd97ReGCan2jbaLvEg-E/edit?skip_itp2_check=true&pli=1#heading=h.wkahme1uqz51

**Comment by jcoyne** [comment]
I have not found that there are any that always fail.

**Comment by mjgiarlo** [comment]
https://github.com/sul-dlss/infrastructure-integration-test/pull/104 moves things along but there remain two problems:

* The create_etd_spec using chrome consistently fails because the disseration upload step never completes. Not sure why.
* The edit_item_tags_spec using chrome fails in different spots. Again, not sure why.

Spent a couple hours chasing down different solutions to both of the above, to no avail. Things we can do to proceed:

1. Remove the chrome driver (:see_no_evil:)
1. Have more :eyes: and :brain: look at these specific failures
1. Do nothing and document the known failures
1. ???

@sul-dlss/infrastructure-team your thoughts?

**Comment by ndushay** [comment]
https://rubydoc.info/github/jnicklas/capybara/master/Capybara%2FNode%2FActions:attach_file - does it need to somehow use a `visible: all` setting?

**Comment by mjgiarlo** [comment]
@ndushay :speech_balloon: 
> [rubydoc.info/github/jnicklas/capybara/master/Capybara%2FNode%2FActions:attach_file](https://rubydoc.info/github/jnicklas/capybara/master/Capybara%2FNode%2FActions:attach_file) - does it need to somehow use a `visible: all` setting? 

Not sure that is "a thing" for `attach_file` (see also what I say below about `make_visible`). Also, we're using `visible: :all` already here: https://github.com/sul-dlss/infrastructure-integration-test/blob/master/spec/features/create_etd_spec.rb#L112

> Oh - and at one point, I was doing a refresh to get the file to show up when I was writing this spec, otherwise it seemed to load forever.

When you refresh the page at this point, the file is not attached and the widget is no longer in progress. :unamused: 

> [stackoverflow.com/questions/53395806/capybara-with-selenium-and-remote-chrome-how-to-attach-file-for-upload](https://stackoverflow.com/questions/53395806/capybara-with-selenium-and-remote-chrome-how-to-attach-file-for-upload)

Yeah, this is one of the three billion links I read over and over again yesterday to no avail. I attempted the `make_visible` arg to `attach_file` and it didn't change anything.
 
> Do you remember specifically which line it is executing when it fails the `create_etd_spec` using chrome?

Line 20 of what's in `master` now:

```ruby
    expect(page).to have_content(dissertation_filename)
```

And indeed the filename is not there because the file upload progress graphic is still loading.

After #104 is merged, I'm unassigning myself from this issue lest it pull me into a vortex from which I will be an ineffective FR this week. :sweat_smile: Happy to consult with whoever picks this up, though!

**Comment by mjgiarlo** [comment]
Discussed in team meeting on 2020/05/27: Remove chrome support for now. Not adding value.
