### ISSUE TITLE
Test catkey editing

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/infrastructure-integration-test#251]
Add an integration test or extend an existing integration test to set the catkey, then set it again, a recent bug only showed up after the initial addition of a catkey so testing that the catkey can be set, and then changed is important.

**Comment by ndushay** [comment]
if the catkey can be STORED after update in docker dor-services-app / fedora, then this can be an argo feature test.  The problem was that the update was not being stored.    If the feature test mocking can uber confidently result in "store" being called with the proper data, then this can be an argo feature test.

Otherwise, it need to be an integration test to be sure that the catkey is:
- updated in SDR
- ?? reindexed ??  (do we index catkeys?)

**Comment by jcoyne** [comment]
There is no need to do any mocking in an argo feature test like this because it has DSA running in a container in the test suite.

**Comment by jcoyne** [comment]
This seems to be very well tested in Argo and doesn't have external dependencies.
